stages:
  - build
  - test

build:
  stage: build
  image: node
  script:
    - echo "Start building App"
    - cd app-client/
    - yarn install
    - yarn run build
    - echo "Build successfully!"

test:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - cd app-client/
    - yarn install
    - yarn run test-all
    - echo "Test successfully!"
