stages:
  - build
  - test
  - docker-compose-build

build-client:
  stage: build
  image: node
  script:
    - echo "Start building Client"
    - cd app-client/
    - yarn install
    - yarn run build
    - echo "Build successfully!"

build-server:
  stage: build
  image: node
  script:
    - echo "Start building Api"
    - cd app-server/
    - yarn install
    - yarn run build
    - echo "Build successfully!"

test-client:
  stage: test
  image: node
  script:
    - echo "Testing Client"
    - cd app-client/
    - yarn install
    - yarn run test-all
    - echo "Test successfully!"

test-server:
  stage: test
  image: node
  script:
    - echo "Testing Api"
    - cd app-server/
    - yarn install
    - yarn run lint
    - yarn run test:cov
    - echo "Test successfully!"

docker-build:
  stage: docker-compose-build
  image: docker
  services:
    - docker:dind
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d
